/** PARAMETERS */
const HORIZON = 7;
const K = 2;
const INVESTOR_ENDOWMENT = 4;
const INVESTEE_ENDOWMENT = 0;
const UNIT_TO_DOLLAR_RATIO = 20;
const LOOKAHEAD = 4;
const COMPREHENSION_LIMIT = 2;

module.exports = {
  HORIZON,
  K,
  INVESTEE_ENDOWMENT,
  INVESTOR_ENDOWMENT,
  UNIT_TO_DOLLAR_RATIO,
  LOOKAHEAD,
  COMPREHENSION_LIMIT
}