#!/bin/bash

echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
echo "TLS=$TLS"
echo "AWS_PROFILE=$AWS_PROFILE"
echo "MTURK=$MTURK"
echo "HITID=$HITID"
echo "MTURK_PROD=$MTURK_PROD"
echo "NAME=$NAME"
echo "DEBUG=$DEBUG"
echo "LOOKAHEAD=$LOOKAHEAD"
echo "HORIZON=$HORIZON"